### ISSUE TITLE
Correct address "RTMP"?

### ISSUE THREAD

**Issue by vitalspace** [davedoesdev/streamana#13]
Correct address "RTMP"?

Hi been trying to test the demo. the problem is that I can't do it. The url that I should enter in the "ingestion url" bar should be something similar to:

`rtmp://a.rtmp.youtube.com/live2/stream-key`

o how?

**Comment by davedoesdev** [comment]
Hi @vitalspace 
I'm afraid RTMP won't work. You should be able to get a HLS ingestion URL from YouTube Studio. From the README:

Get your ingestion URL from YouTube Studio.

Click CREATE and then select Go Live from the drop-down menu.

Under Select stream key, select Create new stream key.

Give your key a name.

You must select HLS as the streaming protocol. Note: YouTube DASH ingestion is only available by using the Youtube API. See here for more details.

Click CREATE.

Make sure the key you created is selected.

Click COPY next to Stream URL.
